services:
  json-tool:
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CI=true
      - DISPLAY=':99.0'
    build:
      context: ./
    volumes:
      - ./:/app
    command: npm run start
