allowBuilds:
  '@parcel/watcher': true
  core-js: true
  cucumber-expressions: true
  cypress: true
  electron-winstaller: true
  es5-ext: true
  esbuild: true
  unrs-resolver: false
patchedDependencies:
  cypress-cucumber-preprocessor@4.3.1: patches/cypress-cucumber-preprocessor@4.3.1.patch
