sonar.projectKey=marabesi_json-tool
sonar.organization=marabesi
sonar.javascript.lcov.reportPaths=./merged_coverage.info
sonar.coverage.exclusions=**/__tests__/**,**/__mocks__/**,**/node_modules/**,**/dist/**,**/coverage/**,**/src/**/*.d.ts,**/cypress/**
