name: Push snap

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to publish to snapstore'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          envFilePath: ./envvars.for.actions

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: install
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: pnpm build

      - name: package
        run: pnpm package

      - name: publish snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: "dist/json-tool_${{ github.event.inputs.version }}_amd64.snap"
          release: beta,candidate,stable
