name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install wine
        run: sudo apt-get install wine
      - name: export display
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
      - name: install
        run: npm install
      - name: test
        run: npm run test
        env:
          CI: true
          DISPLAY: ':99.0'
      - name: package
        run: npm run package
      - name: distribute for linux 64
        uses: actions/upload-artifact@v2
        with:
          name: archive-electron-platform
          path: dist/json-tool-0.1.0.AppImage
