name: Node CI - pull request

on:
  workflow_dispatch:
  pull_request:

env:
  CI: true

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./envvars.for.actions

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Restore node modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: Save the cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}

  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Restore node modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: build
        run: npm run build

  test:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Restore node modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: tests
        run: npm run test

  acceptance:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: export display
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      - name: Run cypress (acceptance tests)
        uses: cypress-io/github-action@v4
        env:
          CI: true
          DISPLAY: ':99.0'
          CYPRESS_BASE_URL: 'http://localhost:3000'
        with:
          wait-on: 'http://localhost:3000'
          start: npm run start
